spring:
  security:
    oauth2.client:
      registration:
        kakao:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope:
            - account_email
            - profile_nickname
            - profile_image
          client-name: Kakao
        google:
          clientId: ${GOOGLE_CLIENT_ID}
          clientSecret: ${GOOGLE_CLIENT_SECRET}
          scope:
            - email
            - profile
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope:
            - name
            - email
            - profile_image
          client-name: Naver
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
        naver:
          authorization_uri: https://nid.naver.com/oauth2.0/authorize
          token_uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user_name_attribute: response

frontend:
  redirectUri: http://localhost:3000/login/oauth2/code/kakao
  authorizedRedirectUris: >
    http://localhost:3000.*,
    https://missulgan.art.*